# Extended curated database of seminal classic literature (pre-2005)
CLASSICS_DATABASE = [
    # --- PHYSICS ---
    {
        "id": "c1",
        "title": "Simulating Physics with Computers",
        "authors": "Richard P. Feynman",
        "year": "1982",
        "category": "Quantum Physics",
        "parent": "Physics",
        "summary": "Feynman proposes using quantum mechanical systems to simulate physical phenomena.",
        "pdf": "https://dspace.mit.edu/bitstream/handle/1721.1/11724/SimulatingPhysicsWithComputers.pdf",
    },
    {
        "id": "c2",
        "title": "On the Electrodynamics of Moving Bodies",
        "authors": "Albert Einstein",
        "year": "1905",
        "category": "Relativity",
        "parent": "Physics",
        "summary": "Einstein introduces special relativity, reconciling Maxwell's equations with relativity principles.",
        "pdf": "https://www.pro-physik.de/restricted-files/87021",
    },
    {
        "id": "c3",
        "title": "Can Quantum-Mechanical Description of Physical Reality be Considered Complete?",
        "authors": "A. Einstein, B. Podolsky, N. Rosen",
        "year": "1935",
        "category": "Quantum Physics",
        "parent": "Physics",
        "summary": "The famous EPR paradox paper introducing quantum entanglement questions.",
        "pdf": "https://journals.aps.org/pr/abstract/10.1103/PhysRev.47.777",
    },
    {
        "id": "c4",
        "title": "On the Einstein Podolsky Rosen Paradox",
        "authors": "J. S. Bell",
        "year": "1964",
        "category": "Quantum Physics",
        "parent": "Physics",
        "summary": "Bell introduces Bell's Theorem, demonstrating that local hidden-variable theories are incompatible with quantum mechanics.",
        "pdf": "https://cds.cern.ch/record/111416/files/vol1p195-200_001.pdf",
    },
    {
        "id": "c5",
        "title": "The Quantum Theory of Radiation",
        "authors": "P. A. M. Dirac",
        "year": "1927",
        "category": "Quantum Physics",
        "parent": "Physics",
        "summary": "Dirac initiates quantum field theory by quantizing the electromagnetic field.",
        "pdf": "https://royalsocietypublishing.org/doi/10.1098/rspa.1927.0039",
    },
    {
        "id": "c6",
        "title": "Thermal Radiation and the Quantum Hypothesis",
        "authors": "Max Planck",
        "year": "1900",
        "category": "Statistical Mechanics",
        "parent": "Physics",
        "summary": "Planck introduces energy quanta to resolve the blackbody radiation problem.",
        "pdf": "https://www.google.com/search?q=Max+Planck+1900+paper+pdf",
    },
    {
        "id": "c7",
        "title": "A Theory of Turbulence",
        "authors": "A. N. Kolmogorov",
        "year": "1941",
        "category": "Fluid Dynamics",
        "parent": "Physics",
        "summary": "Kolmogorov presents his 1941 statistical theory of fully developed turbulent fluid flows.",
        "pdf": "https://www.google.com/search?q=Kolmogorov+1941+turbulence+pdf",
    },
    {
        "id": "c8",
        "title": "The Theory of Positrons",
        "authors": "P. A. M. Dirac",
        "year": "1931",
        "category": "High Energy Physics",
        "parent": "Physics",
        "summary": "Dirac predicts the existence of antimatter (the positron) from relativistic wave equations.",
        "pdf": "https://royalsocietypublishing.org/doi/10.1098/rspa.1931.0130",
    },
    # --- COMPUTER SCIENCE & AI ---
    {
        "id": "c9",
        "title": "Computing Machinery and Intelligence",
        "authors": "Alan M. Turing",
        "year": "1950",
        "category": "Artificial Intelligence",
        "parent": "Computer Science & AI",
        "summary": "Turing introduces the imitation game (Turing Test) and asks: Can machines think?",
        "pdf": "https://www.csee.umbc.edu/courses/471/papers/turing.pdf",
    },
    {
        "id": "c10",
        "title": "A Mathematical Theory of Communication",
        "authors": "Claude E. Shannon",
        "year": "1948",
        "category": "Theory of Computation",
        "parent": "Computer Science & AI",
        "summary": "Shannon lays the foundation for information theory and digital communication.",
        "pdf": "https://math.harvard.edu/~ctm/home/text/others/shannon/entropy/entropy.pdf",
    },
    {
        "id": "c11",
        "title": "Neocognitron: A Self-organizing Neural Network Model",
        "authors": "Kunihiko Fukushima",
        "year": "1980",
        "category": "Machine Learning",
        "parent": "Computer Science & AI",
        "summary": "Fukushima introduces the precursor to modern Convolutional Neural Networks.",
        "pdf": "https://www.google.com/search?q=Fukushima+Neocognitron+1980+pdf",
    },
    # --- PSYCHOLOGY & COGNITIVE SCIENCE ---
    {
        "id": "c12",
        "title": "Principles of Topological Psychology",
        "authors": "Kurt Lewin",
        "year": "1936",
        "category": "General Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "Lewin applies mathematical topology concepts to human behavior and psychological field theory.",
        "pdf": "https://www.google.com/search?q=Kurt+Lewin+Principles+of+Topological+Psychology",
    },
    {
        "id": "c13",
        "title": "The Magical Number Seven, Plus or Minus Two",
        "authors": "George A. Miller",
        "year": "1956",
        "category": "Cognitive Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "Miller proposes that human short-term memory capacity is limited to roughly seven chunks.",
        "pdf": "https://psychclassics.yorku.ca/Miller/",
    },
    {
        "id": "c14",
        "title": "Transmission of Aggression Through Imitation of Aggressive Models",
        "authors": "Albert Bandura",
        "year": "1961",
        "category": "Social Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "The famous Bobo doll experiment detailing social learning theory in children.",
        "pdf": "https://www.google.com/search?q=Bandura+1961+Bobo+Doll+pdf",
    },
]