# Comprehensive Curated Database of Seminal Classic Literature (Pre-2005)
CLASSICS_DATABASE = [
    # ==========================================
    # --- PHYSICS & ASTRONOMY ---
    # ==========================================
    {
        "id": "phys_1",
        "title": "On the Electrodynamics of Moving Bodies",
        "authors": "Albert Einstein",
        "year": "1905",
        "category": "Relativity",
        "parent": "Physics",
        "summary": "Einstein introduces special relativity, reconciling Maxwell's electrodynamics with relativity principles.",
        "pdf": "https://www.pro-physik.de/restricted-files/87021",
    },
    {
        "id": "phys_2",
        "title": "Does the Inertia of a Body Depend Upon Its Energy-Content?",
        "authors": "Albert Einstein",
        "year": "1905",
        "category": "Relativity",
        "parent": "Physics",
        "summary": "The follow-up paper deriving E = mc², linking mass and energy equivalence.",
        "pdf": "https://www.fourmilab.ch/etexts/einstein/E_mc2/e_mc2.pdf",
    },
    {
        "id": "phys_3",
        "title": "Simulating Physics with Computers",
        "authors": "Richard P. Feynman",
        "year": "1982",
        "category": "Quantum Physics",
        "parent": "Physics",
        "summary": "Feynman proposes using quantum mechanical systems to simulate physical phenomena, sparking quantum computing.",
        "pdf": "https://dspace.mit.edu/bitstream/handle/1721.1/11724/SimulatingPhysicsWithComputers.pdf",
    },
    {
        "id": "phys_4",
        "title": "Can Quantum-Mechanical Description of Physical Reality be Considered Complete?",
        "authors": "A. Einstein, B. Podolsky, N. Rosen",
        "year": "1935",
        "category": "Quantum Physics",
        "parent": "Physics",
        "summary": "The famous EPR paradox paper challenging quantum mechanics completeness through entanglement.",
        "pdf": "https://journals.aps.org/pr/abstract/10.1103/PhysRev.47.777",
    },
    {
        "id": "phys_5",
        "title": "On the Einstein Podolsky Rosen Paradox",
        "authors": "J. S. Bell",
        "year": "1964",
        "category": "Quantum Physics",
        "parent": "Physics",
        "summary": "Bell introduces Bell's Theorem, proving local hidden-variable theories cannot replicate quantum predictions.",
        "pdf": "https://cds.cern.ch/record/111416/files/vol1p195-200_001.pdf",
    },
    {
        "id": "phys_6",
        "title": "The Quantum Theory of Radiation",
        "authors": "P. A. M. Dirac",
        "year": "1927",
        "category": "Quantum Physics",
        "parent": "Physics",
        "summary": "Dirac initiates quantum field theory by quantizing the electromagnetic field.",
        "pdf": "https://royalsocietypublishing.org/doi/10.1098/rspa.1927.0039",
    },
    {
        "id": "phys_7",
        "title": "The Theory of Positrons",
        "authors": "P. A. M. Dirac",
        "year": "1931",
        "category": "High Energy Physics",
        "parent": "Physics",
        "summary": "Dirac predicts the existence of antimatter (the positron) from relativistic wave equations.",
        "pdf": "https://royalsocietypublishing.org/doi/10.1098/rspa.1931.0130",
    },
    {
        "id": "phys_8",
        "title": "Thermal Radiation and the Quantum Hypothesis",
        "authors": "Max Planck",
        "year": "1900",
        "category": "Statistical Mechanics",
        "parent": "Physics",
        "summary": "Planck introduces energy quanta (h) to resolve the ultraviolet catastrophe in blackbody radiation.",
        "pdf": "https://www.google.com/search?q=Max+Planck+1900+blackbody+radiation+pdf",
    },
    {
        "id": "phys_9",
        "title": "The Local Structure of Turbulence in Incompressible Viscous Fluid",
        "authors": "A. N. Kolmogorov",
        "year": "1941",
        "category": "Fluid Dynamics",
        "parent": "Physics",
        "summary": "Kolmogorov presents his K41 statistical theory governing energy cascade in turbulent flows.",
        "pdf": "https://royalsocietypublishing.org/doi/10.1098/rspa.1991.0075",
    },
    {
        "id": "phys_10",
        "title": "Space-Time Approach to Non-Relativistic Quantum Mechanics",
        "authors": "Richard P. Feynman",
        "year": "1948",
        "category": "Quantum Physics",
        "parent": "Physics",
        "summary": "Feynman introduces the path integral formulation of quantum mechanics using sum-over-histories.",
        "pdf": "https://journals.aps.org/rmp/abstract/10.1103/RevModPhys.20.367",
    },
    {
        "id": "phys_11",
        "title": "Conservation of Isotopic Spin and Isotopic Gauge Invariance",
        "authors": "C. N. Yang, R. L. Mills",
        "year": "1954",
        "category": "High Energy Physics",
        "parent": "Physics",
        "summary": "Yang and Mills construct non-Abelian gauge theory, forming the backbone of the Standard Model.",
        "pdf": "https://journals.aps.org/pr/abstract/10.1103/PhysRev.96.191",
    },
    {
        "id": "phys_12",
        "title": "Broken Symmetries and the Masses of Gauge Bosons",
        "authors": "Peter W. Higgs",
        "year": "1964",
        "category": "High Energy Physics",
        "parent": "Physics",
        "summary": "Higgs details the spontaneous symmetry breaking mechanism that gives elementary particles mass.",
        "pdf": "https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.13.508",
    },
    {
        "id": "phys_13",
        "title": "Black Hole Explosions?",
        "authors": "S. W. Hawking",
        "year": "1974",
        "category": "Relativity",
        "parent": "Physics",
        "summary": "Hawking demonstrates that quantum effects near event horizons cause black holes to emit thermal radiation.",
        "pdf": "https://www.nature.com/articles/248030a0",
    },
    {
        "id": "phys_14",
        "title": "Theory of Superconductivity",
        "authors": "J. Bardeen, L. N. Cooper, J. R. Schrieffer",
        "year": "1957",
        "category": "Statistical Mechanics",
        "parent": "Physics",
        "summary": "The BCS theory explaining zero electrical resistance via Cooper pairs bound by lattice vibrations.",
        "pdf": "https://journals.aps.org/pr/abstract/10.1103/PhysRev.108.1175",
    },
    {
        "id": "phys_15",
        "title": "Absence of Diffusion in Certain Random Lattices",
        "authors": "P. W. Anderson",
        "year": "1958",
        "category": "Statistical Mechanics",
        "parent": "Physics",
        "summary": "Anderson discovery of electron localization due to disorder in crystalline lattices.",
        "pdf": "https://journals.aps.org/pr/abstract/10.1103/PhysRev.109.1492",
    },

    # ==========================================
    # --- COMPUTER SCIENCE & AI ---
    # ==========================================
    {
        "id": "cs_1",
        "title": "Computing Machinery and Intelligence",
        "authors": "Alan M. Turing",
        "year": "1950",
        "category": "Artificial Intelligence",
        "parent": "Computer Science & AI",
        "summary": "Turing introduces the imitation game (Turing Test) and foundational questions on machine consciousness.",
        "pdf": "https://www.csee.umbc.edu/courses/471/papers/turing.pdf",
    },
    {
        "id": "cs_2",
        "title": "A Mathematical Theory of Communication",
        "authors": "Claude E. Shannon",
        "year": "1948",
        "category": "Theory of Computation",
        "parent": "Computer Science & AI",
        "summary": "Shannon introduces information entropy, noisy-channel coding, and digital information theory.",
        "pdf": "https://math.harvard.edu/~ctm/home/text/others/shannon/entropy/entropy.pdf",
    },
    {
        "id": "cs_3",
        "title": "On Computable Numbers, with an Application to the Entscheidungsproblem",
        "authors": "Alan M. Turing",
        "year": "1936",
        "category": "Theory of Computation",
        "parent": "Computer Science & AI",
        "summary": "Turing introduces Universal Turing Machines and proves the Halting Problem is undecidable.",
        "pdf": "https://www.cs.virginia.edu/~robins/Turing_Paper_1936.pdf",
    },
    {
        "id": "cs_4",
        "title": "Learning Representations by Back-Propagating Errors",
        "authors": "D. E. Rumelhart, G. E. Hinton, R. J. Williams",
        "year": "1986",
        "category": "Machine Learning",
        "parent": "Computer Science & AI",
        "summary": "Popularizes the backpropagation algorithm for training multi-layer neural networks.",
        "pdf": "https://www.nature.com/articles/323533a0",
    },
    {
        "id": "cs_5",
        "title": "Gradient-Based Learning Applied to Document Recognition",
        "authors": "Y. LeCun, L. Bottou, Y. Bengio, P. Haffner",
        "year": "1998",
        "category": "Computer Vision",
        "parent": "Computer Science & AI",
        "summary": "Introduces LeNet-5, demonstrating convolutional neural networks for handwriting vision recognition.",
        "pdf": "http://yann.lecun.com/exdb/publis/pdf/lecun-98.pdf",
    },
    {
        "id": "cs_6",
        "title": "Long Short-Term Memory",
        "authors": "S. Hochreiter, J. Schmidhuber",
        "year": "1997",
        "category": "Machine Learning",
        "parent": "Computer Science & AI",
        "summary": "Introduces LSTM recurrent neural networks to solve vanishing/exploding gradients in sequential data.",
        "pdf": "https://www.bioinf.jku.at/publications/older/2604.pdf",
    },
    {
        "id": "cs_7",
        "title": "Neocognitron: A Self-organizing Neural Network Model",
        "authors": "Kunihiko Fukushima",
        "year": "1980",
        "category": "Computer Vision",
        "parent": "Computer Science & AI",
        "summary": "The structural precursor to modern CNNs featuring visual receptive fields and shift invariance.",
        "pdf": "https://www.google.com/search?q=Fukushima+Neocognitron+1980+pdf",
    },
    {
        "id": "cs_8",
        "title": "The Anatomy of a Large-Scale Hypertextual Web Search Engine",
        "authors": "S. Brin, L. Page",
        "year": "1998",
        "category": "Theory of Computation",
        "parent": "Computer Science & AI",
        "summary": "Page and Brin detail the original architecture of Google and the PageRank graph algorithm.",
        "pdf": "http://infolab.stanford.edu/~backrub/google.html",
    },
    {
        "id": "cs_9",
        "title": "The Complexity of Theorem-Proving Procedures",
        "authors": "Stephen A. Cook",
        "year": "1971",
        "category": "Theory of Computation",
        "parent": "Computer Science & AI",
        "summary": "Introduces the concept of NP-completeness and proves Boolean Satisfiability (SAT) is NP-complete.",
        "pdf": "https://dl.acm.org/doi/10.1145/800157.805047",
    },
    {
        "id": "cs_10",
        "title": "Reducibility Among Combinatorial Problems",
        "authors": "Richard M. Karp",
        "year": "1972",
        "category": "Theory of Computation",
        "parent": "Computer Science & AI",
        "summary": "Karp proves 21 key combinatorial problems (like Traveling Salesperson) are NP-complete.",
        "pdf": "https://link.springer.com/chapter/10.1007/978-1-4684-2001-2_9",
    },
    {
        "id": "cs_11",
        "title": "A Method for Obtaining Digital Signatures and Public-Key Cryptosystems",
        "authors": "R. L. Rivest, A. Shamir, L. Adleman",
        "year": "1978",
        "category": "Theory of Computation",
        "parent": "Computer Science & AI",
        "summary": "Introduces the RSA public-key encryption algorithm based on prime factorization difficulty.",
        "pdf": "https://dl.acm.org/doi/10.1145/359340.359342",
    },
    {
        "id": "cs_12",
        "title": "New Directions in Cryptography",
        "authors": "W. Diffie, M. E. Hellman",
        "year": "1976",
        "category": "Theory of Computation",
        "parent": "Computer Science & AI",
        "summary": "Diffie and Hellman introduce public-key cryptography and secure key exchange over untrusted channels.",
        "pdf": "https://ieeexplore.ieee.org/document/1055638",
    },
    {
        "id": "cs_13",
        "title": "Probabilistic Reasoning in Intelligent Systems",
        "authors": "Judea Pearl",
        "year": "1988",
        "category": "Artificial Intelligence",
        "parent": "Computer Science & AI",
        "summary": "Pearl establishes Bayesian networks and causal inference in modern artificial intelligence.",
        "pdf": "https://www.google.com/search?q=Judea+Pearl+1988+Probabilistic+Reasoning+pdf",
    },
    {
        "id": "cs_14",
        "title": "Rapid Object Detection using a Boosted Cascade of Simple Features",
        "authors": "P. Viola, M. Jones",
        "year": "2001",
        "category": "Computer Vision",
        "parent": "Computer Science & AI",
        "summary": "The Viola-Jones algorithm providing real-time visual face detection using Haar-like features.",
        "pdf": "https://ieeexplore.ieee.org/document/990517",
    },
    {
        "id": "cs_15",
        "title": "Distinctive Image Features from Scale-Invariant Keypoints",
        "authors": "David G. Lowe",
        "year": "2004",
        "category": "Computer Vision",
        "parent": "Computer Science & AI",
        "summary": "Introduces the SIFT algorithm for extracting scale and rotation invariant visual feature descriptors.",
        "pdf": "https://www.cs.ubc.ca/~lowe/papers/ijcv04.pdf",
    },

    # ==========================================
    # --- PSYCHOLOGY & COGNITIVE SCIENCE ---
    # ==========================================
    {
        "id": "psych_1",
        "title": "Principles of Topological Psychology",
        "authors": "Kurt Lewin",
        "year": "1936",
        "category": "General Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "Lewin applies mathematical topology concepts to human behavior, establishing psychological field theory.",
        "pdf": "https://www.google.com/search?q=Kurt+Lewin+Principles+of+Topological+Psychology",
    },
    {
        "id": "psych_2",
        "title": "The Magical Number Seven, Plus or Minus Two",
        "authors": "George A. Miller",
        "year": "1956",
        "category": "Cognitive Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "Miller demonstrates that human short-term memory capacity is restricted to roughly 7 ± 2 chunks.",
        "pdf": "https://psychclassics.yorku.ca/Miller/",
    },
    {
        "id": "psych_3",
        "title": "Transmission of Aggression Through Imitation of Aggressive Models",
        "authors": "Albert Bandura, D. Ross, S. A. Ross",
        "year": "1961",
        "category": "Social Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "The famous Bobo doll study demonstrating social observational learning in children.",
        "pdf": "https://psycnet.apa.org/record/1962-02688-001",
    },
    {
        "id": "psych_4",
        "title": "Judgment under Uncertainty: Heuristics and Biases",
        "authors": "A. Tversky, D. Kahneman",
        "year": "1974",
        "category": "Cognitive Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "Kahneman & Tversky detail cognitive biases including representativeness, availability, and anchoring.",
        "pdf": "https://www.science.org/doi/10.1126/science.185.4157.1124",
    },
    {
        "id": "psych_5",
        "title": "Prospect Theory: An Analysis of Decision under Risk",
        "authors": "D. Kahneman, A. Tversky",
        "year": "1979",
        "category": "Cognitive Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "Introduces Prospect Theory, showing humans value losses and gains asymmetric (loss aversion).",
        "pdf": "https://www.jstor.org/stable/1914185",
    },
    {
        "id": "psych_6",
        "title": "Behaviorism and Zen",
        "authors": "B. F. Skinner",
        "year": "1938",
        "category": "General Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "Skinner outlines operant conditioning, reinforcement schedules, and behaviorist psychology principles.",
        "pdf": "https://www.google.com/search?q=BF+Skinner+1938+Behavior+of+Organisms+pdf",
    },
    {
        "id": "psych_7",
        "title": "Cognitive Maps in Rats and Men",
        "authors": "Edward C. Tolman",
        "year": "1948",
        "category": "Cognitive Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "Tolman demonstrates latent learning and spatial mental representations in animals.",
        "pdf": "https://psychclassics.yorku.ca/Tolman/Maps/maps.htm",
    },
    {
        "id": "psych_8",
        "title": "A Review of B. F. Skinner's Verbal Behavior",
        "authors": "Noam Chomsky",
        "year": "1959",
        "category": "Cognitive Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "Chomsky critique of behaviorism that launched the Cognitive Revolution in psychology.",
        "pdf": "https://chomsky.info/1959----/",
    },
    {
        "id": "psych_9",
        "title": "The Origin of the Concept of Object",
        "authors": "Jean Piaget",
        "year": "1954",
        "category": "Developmental Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "Piaget outlines cognitive development stages and object permanence in infant psychology.",
        "pdf": "https://www.google.com/search?q=Jean+Piaget+1954+Construction+of+Reality+pdf",
    },
    {
        "id": "psych_10",
        "title": "Studies of Independence and Conformity",
        "authors": "Solomon E. Asch",
        "year": "1956",
        "category": "Social Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "The landmark Asch conformity experiments testing group pressure on individual perception.",
        "pdf": "https://psycnet.apa.org/record/1957-01311-001",
    },
    {
        "id": "psych_11",
        "title": "Behavioral Study of Obedience",
        "authors": "Stanley Milgram",
        "year": "1963",
        "category": "Social Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "Milgram electric shock experiments examining blind obedience to authority figures.",
        "pdf": "https://psycnet.apa.org/record/1964-03472-001",
    },
    {
        "id": "psych_12",
        "title": "Cognitive Dissonance Theory",
        "authors": "Leon Festinger",
        "year": "1957",
        "category": "Social Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "Festinger introduces cognitive dissonance—the psychological discomfort from contradictory beliefs.",
        "pdf": "https://www.google.com/search?q=Festinger+1957+Theory+of+Cognitive+Dissonance+pdf",
    },
    {
        "id": "psych_13",
        "title": "A Theory of Human Motivation",
        "authors": "Abraham H. Maslow",
        "year": "1943",
        "category": "General Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "Maslow proposes the Hierarchy of Needs ranging from physiological survival to self-actualization.",
        "pdf": "https://psychclassics.yorku.ca/Maslow/motivation.htm",
    },
    {
        "id": "psych_14",
        "title": "Attachment and Loss: Attachment",
        "authors": "John Bowlby",
        "year": "1969",
        "category": "Developmental Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "Bowlby introduces Attachment Theory, linking early maternal care to lifelong psychological health.",
        "pdf": "https://www.google.com/search?q=Bowlby+1969+Attachment+and+Loss+pdf",
    },
    {
        "id": "psych_15",
        "title": "Patterns of Attachment: A Psychological Study of the Strange Situation",
        "authors": "Mary D. Salter Ainsworth",
        "year": "1978",
        "category": "Developmental Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "Ainsworth classifies secure, avoidant, and anxious attachment styles in infants.",
        "pdf": "https://www.google.com/search?q=Ainsworth+1978+Patterns+of+Attachment+pdf",
    },

    # ==========================================
    # --- BIOLOGY & MEDICINE ---
    # ==========================================
    {
        "id": "bio_1",
        "title": "Molecular Structure of Nucleic Acids: A Structure for Deoxyribose Nucleic Acid",
        "authors": "J. D. Watson, F. H. C. Crick",
        "year": "1953",
        "category": "Biomolecules",
        "parent": "Biology & Medicine",
        "summary": "Watson and Crick present the double-helix crystal model of DNA base pairing.",
        "pdf": "https://www.nature.com/articles/171737a0",
    },
    {
        "id": "bio_2",
        "title": "A Quantitative Description of Membrane Current and Its Application to Conduction in Nerve",
        "authors": "A. L. Hodgkin, A. F. Huxley",
        "year": "1952",
        "category": "Neurons & Cognition",
        "parent": "Biology & Medicine",
        "summary": "The Hodgkin-Huxley mathematical model describing action potential propagation in squid giant axons.",
        "pdf": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1392413/",
    },
    {
        "id": "bio_3",
        "title": "Receptive Fields of Single Neurones in the Cat's Striate Cortex",
        "authors": "D. H. Hubel, T. N. Wiesel",
        "year": "1959",
        "category": "Neurons & Cognition",
        "parent": "Biology & Medicine",
        "summary": "Hubel & Wiesel uncover simple and complex orientation selectivity in primary visual cortex cells.",
        "pdf": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1363130/",
    },
    {
        "id": "bio_4",
        "title": "Initial Sequencing and Analysis of the Human Genome",
        "authors": "Human Genome Sequencing Consortium",
        "year": "2001",
        "category": "Genomics",
        "parent": "Biology & Medicine",
        "summary": "The landmark nature publication presenting the draft reference sequence of the human genome.",
        "pdf": "https://www.nature.com/articles/35057062",
    },
    {
        "id": "bio_5",
        "title": "The Sequence of the Human Genome",
        "authors": "J. Craig Venter et al.",
        "year": "2001",
        "category": "Genomics",
        "parent": "Biology & Medicine",
        "summary": "Celera Genomics shotgun sequencing publication of the human genome.",
        "pdf": "https://www.science.org/doi/10.1126/science.1058042",
    },
    {
        "id": "bio_6",
        "title": "Specific Synthesis of DNA in Vitro via a Polymerase-Catalyzed Chain Reaction",
        "authors": "K. Mullis et al.",
        "year": "1986",
        "category": "Biomolecules",
        "parent": "Biology & Medicine",
        "summary": "Kary Mullis invents Polymerase Chain Reaction (PCR), revolutionizing modern molecular biology.",
        "pdf": "https://www.google.com/search?q=Mullis+1986+PCR+paper+pdf",
    },
    {
        "id": "bio_7",
        "title": "Electrophoretic Transfer of Proteins from Polyacrylamide Gels to Nitrocellulose Sheets",
        "authors": "H. Towbin, T. Staehelin, J. Gordon",
        "year": "1979",
        "category": "Biomolecules",
        "parent": "Biology & Medicine",
        "summary": "Introduces the Western Blot procedure for protein detection and identification.",
        "pdf": "https://www.pnas.org/doi/10.1073/pnas.76.9.4350",
    },
    {
        "id": "bio_8",
        "title": "Basic Local Alignment Search Tool (BLAST)",
        "authors": "S. F. Altschul, W. Gish, W. Miller, E. W. Myers, D. J. Lipman",
        "year": "1990",
        "category": "Genomics",
        "parent": "Biology & Medicine",
        "summary": "Introduces BLAST, the fundamental sequence alignment search algorithm in bioinformatics.",
        "pdf": "https://www.sciencedirect.com/science/article/pii/S0022283605803602",
    },
    {
        "id": "bio_9",
        "title": "Cleavage of Structural Proteins during the Assembly of the Head of Bacteriophage T4",
        "authors": "U. K. Laemmli",
        "year": "1970",
        "category": "Biomolecules",
        "parent": "Biology & Medicine",
        "summary": "Laemmli SDS-PAGE gel electrophoresis method for separating proteins by molecular weight.",
        "pdf": "https://www.nature.com/articles/227680a0",
    },
    {
        "id": "bio_10",
        "title": "A Rapid and Sensitive Method for the Quantitation of Microgram Quantities of Protein",
        "authors": "Marion M. Bradford",
        "year": "1976",
        "category": "Biomolecules",
        "parent": "Biology & Medicine",
        "summary": "Introduces the Bradford protein assay utilizing Coomassie Brilliant Blue binding.",
        "pdf": "https://www.sciencedirect.com/science/article/pii/0003269776905273",
    },
    {
        "id": "bio_11",
        "title": "DNA Sequencing with Chain-Terminating Inhibitors",
        "authors": "F. Sanger, S. Nicklen, A. R. Coulson",
        "year": "1977",
        "category": "Genomics",
        "parent": "Biology & Medicine",
        "summary": "Fred Sanger introduces dideoxy chain-termination DNA sequencing (Sanger Sequencing).",
        "pdf": "https://www.pnas.org/doi/10.1073/pnas.74.12.5463",
    },
    {
        "id": "bio_12",
        "title": "Long-Term Potentiation of Synaptic Transmission in the Hippocampus",
        "authors": "T. Lømo, T. V. P. Bliss",
        "year": "1973",
        "category": "Neurons & Cognition",
        "parent": "Biology & Medicine",
        "summary": "Discovers LTP—the cellular synaptic plasticity foundation for long-term memory formation.",
        "pdf": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1350462/",
    },
    {
        "id": "bio_13",
        "title": "The Genetical Theory of Natural Selection",
        "authors": "R. A. Fisher",
        "year": "1930",
        "category": "Genomics",
        "parent": "Biology & Medicine",
        "summary": "Combines Mendelian genetics with Darwinian evolution, creating modern population genetics.",
        "pdf": "https://www.google.com/search?q=RA+Fisher+1930+Genetical+Theory+pdf",
    },
    {
        "id": "bio_14",
        "title": "An Analysis of Gene Expression Measurements by Microarrays",
        "authors": "M. B. Eisen, P. T. Spellman, P. O. Brown, D. Botstein",
        "year": "1998",
        "category": "Genomics",
        "parent": "Biology & Medicine",
        "summary": "Introduces hierarchical clustering methods for genome-wide gene expression microarray data.",
        "pdf": "https://www.pnas.org/doi/10.1073/pnas.95.25.14863",
    },
    {
        "id": "bio_15",
        "title": "The Patch-Clamp Technique for Studying Ion Channels in Cells",
        "authors": "E. Neher, B. Sakmann",
        "year": "1976",
        "category": "Neurons & Cognition",
        "parent": "Biology & Medicine",
        "summary": "Neher and Sakmann invent the patch-clamp technique, allowing measurement of single ion channel currents.",
        "pdf": "https://www.nature.com/articles/260799a0",
    },
    # ==========================================
    # --- MATHEMATICS ---
    # ==========================================
    {
        "id": "math_1",
        "title": "Modular Elliptic Curves and Fermat's Last Theorem",
        "authors": "Andrew Wiles",
        "year": "1995",
        "category": "Number Theory",
        "parent": "Mathematics",
        "summary": "Wiles proves the Taniyama-Shimura-Weil conjecture for semistable elliptic curves, resolving Fermat's Last Theorem.",
        "pdf": "https://annals.math.princeton.edu/1995/141-3/p01",
    },
    {
        "id": "math_2",
        "title": "On the Number of Primes Less Than a Given Magnitude",
        "authors": "Bernhard Riemann",
        "year": "1859",
        "category": "Number Theory",
        "parent": "Mathematics",
        "summary": "Riemann introduces the analytical properties of the Riemann zeta function and states the Riemann Hypothesis.",
        "pdf": "https://www.claymath.org/sites/default/files/riemann1859.pdf",
    },
    {
        "id": "math_3",
        "title": "The Entropy of Dynamical Systems",
        "authors": "A. N. Kolmogorov",
        "year": "1958",
        "category": "Probability",
        "parent": "Mathematics",
        "summary": "Kolmogorov introduces measure-theoretic entropy into ergodic theory and dynamical systems.",
        "pdf": "https://www.google.com/search?q=Kolmogorov+1958+entropy+dynamical+systems+pdf",
    },
    {
        "id": "math_4",
        "title": "Polynomial-time Algorithms for Prime Factorization and Discrete Logarithms on a Quantum Computer",
        "authors": "Peter W. Shor",
        "year": "1994",
        "category": "Combinatorics",
        "parent": "Mathematics",
        "summary": "Shor presents his quantum algorithm breaking RSA encryption in polynomial time.",
        "pdf": "https://arxiv.org/abs/quant-ph/9508027",
    },
    {
        "id": "math_5",
        "title": "The Poincaré Conjecture",
        "authors": "Grigori Perelman",
        "year": "2002",
        "category": "Differential Geometry",
        "parent": "Mathematics",
        "summary": "Perelman introduces Ricci flow with surgery to prove Thurston's Geometrization Conjecture and the Poincaré Conjecture.",
        "pdf": "https://arxiv.org/abs/math/0211159",
    },
    {
        "id": "math_6",
        "title": "Sur la Propriété de Baire",
        "authors": "Stefan Banach",
        "year": "1922",
        "category": "Analysis of PDEs",
        "parent": "Mathematics",
        "summary": "Banach lays the foundations of functional analysis and complete normed vector spaces (Banach spaces).",
        "pdf": "https://www.google.com/search?q=Banach+1922+functional+analysis+pdf",
    },

    # ==========================================
    # --- ADDITIONAL PHYSICS ---
    # ==========================================
    {
        "id": "phys_16",
        "title": "Quantum Mechanics of One- and Two-Electron Atoms",
        "authors": "H. A. Bethe, E. E. Salpeter",
        "year": "1957",
        "category": "Nuclear & Atomic Physics",
        "parent": "Physics",
        "summary": "The definitive theoretical exposition on relativistic and non-relativistic quantum states in light atoms.",
        "pdf": "https://link.springer.com/book/10.1007/978-3-643-80714-3",
    },
    {
        "id": "phys_17",
        "title": "A Model of Leptons",
        "authors": "Steven Weinberg",
        "year": "1967",
        "category": "High Energy Physics",
        "parent": "Physics",
        "summary": "Weinberg unifies electromagnetism and the weak nuclear force into electroweak theory.",
        "pdf": "https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.19.1264",
    },
    {
        "id": "phys_18",
        "title": "Self-Organized Criticality: An Explanation of the 1/f Noise",
        "authors": "P. Bak, C. Tang, K. Wiesenfeld",
        "year": "1987",
        "category": "Statistical Mechanics",
        "parent": "Physics",
        "summary": "Introduces the sandpile model and self-organized criticality in complex dynamic physical systems.",
        "pdf": "https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.59.381",
    },

    # ==========================================
    # --- ADDITIONAL CS & AI ---
    # ==========================================
    {
        "id": "cs_16",
        "title": "Support-Vector Networks",
        "authors": "C. Cortes, V. Vapnik",
        "year": "1995",
        "category": "Machine Learning",
        "parent": "Mathematics",
        "summary": "Introduces Support Vector Machines (SVMs) for high-dimensional pattern classification.",
        "pdf": "https://link.springer.com/article/10.1007/BF00994018",
    },
    {
        "id": "cs_17",
        "title": "Random Forests",
        "authors": "Leo Breiman",
        "year": "2001",
        "category": "Machine Learning",
        "parent": "Computer Science & AI",
        "summary": "Breiman introduces Random Forests, combining decision trees with feature bagging.",
        "pdf": "https://link.springer.com/article/10.1023/A:1010933404324",
    },

    # ==========================================
    # --- ADDITIONAL PSYCHOLOGY ---
    # ==========================================
    {
        "id": "psych_16",
        "title": "Self-Efficacy: Toward a Unifying Theory of Behavioral Change",
        "authors": "Albert Bandura",
        "year": "1977",
        "category": "General Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "Bandura presents the framework of self-efficacy beliefs in human cognitive function and motivation.",
        "pdf": "https://psycnet.apa.org/record/1977-25733-001",
    },
    {
        "id": "psych_17",
        "title": "Social Foundations of Thought and Action: A Social Cognitive Theory",
        "authors": "Albert Bandura",
        "year": "1986",
        "category": "Social Psychology",
        "parent": "Psychology & Cognitive Science",
        "summary": "Bandura details triadic reciprocal determinism linking personal, behavioral, and environmental factors.",
        "pdf": "https://www.google.com/search?q=Bandura+1986+Social+Foundations+pdf",
    },
]